export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';

export const CHANGE_DIRECTORY = 'CHANGE_DIRECTORY';
export const NAVIGATE_SIGNUP = 'NAVIGATE_SIGNUP';
export const NAVIGATE_SIGNIN = 'NAVIGATE_SIGNIN';
